### PR TITLE
Fix a bug where forkedTemplateSandbox.git is undefined

### LINKED ISSUE #4581: 💥 Crash Report
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 6282ca79a          |

  **Route:**
  https://codesandbox.io/s/react-lottie-4cv3t?file=/src/LottieSVG.js

  **Error Code:**
0cb6d61859e94e70b270d5a96c812401

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'git' of null
  TypeError: Cannot read property 'git' of null
    at github (https://codesandbox.io/static/js/app.29c43e1fb.js?_sw-precache=02a4423c2e39fee8494e772e30fe3e4d:551:1247840)
    at ua (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1735721)
    at Es (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1780984)
    at ml (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766560)
    at hl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1766485)
    at il (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1763813)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721996
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1797332)
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721705)
    at Yo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721941)
    at $o (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1721876)
    at se (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1791084)
    at Sn (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js:1:1705502)
  
    in github
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by CompuIves**
We were checking for `git`, but not using the `git` property from that same object.

Fixes #4581

### CODE REVIEW

File: packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx [hunk 1]
```diff
@@ -205,11 +205,10 @@ export const GitHub = () => {
         <Collapsible title="GitHub Repository" defaultOpen>
           <Element paddingX={2}>
             <Text variant="muted">
-              If you wish to contribute back to{' '}
-              {forkedTemplateSandbox.git.username}/
-              {forkedTemplateSandbox.git.repo}, you can link this sandbox to the
-              git repository. This will allow you to create commits and open
-              pull requests with this sandbox.
+              If you wish to contribute back to {upstreamSandbox.git.username}/
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/GitHub/index.tsx:208]: Better context:

image

there's a check here on `upstreamSandbox?.git`, which we weren't using in the text.

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4584/commits/0a5b86f1557c296b6096cc66a4bcf3c13a1955b5 is at https://pr4584.build.csb.dev/s/new.
