### PR TITLE
fix: decouple experimental flag from feedback form

### LINKED ISSUE #8196: Cannot disable beta sandbox editor
# 🐛 bug report

## Preflight Checklist

- [X] I have read the [Contributing Guidelines][contributing] for this project.
- [X] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I can't disable the beta editor (which is an awful experience thus far)

## How has this issue affected you? What are you trying to accomplish?

Revert to old editor

### To Reproduce

Go into account -> Preferences -> Experiments -> Sandbox editor beta -> try to disable -> select a reason -> submit -> still enabled
image

https://github.com/codesandbox/codesandbox-client/assets/25180830/f8b9b2cb-b2c9-4c13-ae59-8d5660bb26e6

### Link to sandbox: [link]() (optional) 
N/A

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       unsure      |
| Browser          |     latest chrome       |
| Operating System |      latest OSX      |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by alexnm**
Closes #8196

### CODE REVIEW

**Comment by danilowoz** [comment]
ohh it still doesn't work for me :( 

https://github.com/codesandbox/codesandbox-client/assets/4838076/6966cc78-8b9d-4a4a-871e-ac42ecf8df5b

File: packages/app/src/app/hooks/usePersistedState.ts [hunk 1]
```diff
@@ -41,13 +41,13 @@ const usePersistedState = <T>(
   useEffect(
     () =>
       browser.storage.subscribe<T>(key, updatedValue => {
-        if (updatedValue) {
-          setStoredValue(updatedValue);
-        } else {
+        if (updatedValue === undefined) {
```
Comment (alexnm) [inline packages/app/src/app/hooks/usePersistedState.ts:44]: This was the problem

**Review by danilowoz — APPROVED** [review]
