### PR TITLE
Fix loading angular resources from node_modules

### LINKED ISSUE #3326: Error: /src/styles.css hasn't been transpiled yet.
# 🐛 bug report
When adding CSS assets to angular-cli.json, the console reports `Error: /src/styles.css hasn't been transpiled yet.`.

## Description of the problem
Steps to reproduce:

1. Start a new CodeSandbox
2. Add `mgl-mapbox-gl` and `mapbox-gl` dependencies
3. Add required CSS files to angular-cli.json
`"./node_modules/mapbox-gl/dist/mapbox-gl.css",
 "./node_modules/@mapbox/mapbox-gl-geocoder/lib/mapbox-gl-geocoder.css"
`
4. Error in console: `Error: /src/styles.css hasn't been transpiled yet.`

## How has this issue affected you? What are you trying to accomplish?
I'm trying to use CodeSandbox to highlight a bug in another app. Funny, that. 😏

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/polished-shadow-sfdsf

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Version 1.2.42 Chromium: 79.0.3945.117 (Official Build) (64-bit)
| Operating System | Windows 10 x64 build 1909

### PR DESCRIPTION
**Pull request by CompuIves**
Fixes #3326

### CODE REVIEW

File: packages/app/src/sandbox/eval/transpiled-module.ts [hunk 1]
```diff
@@ -565,160 +565,170 @@ export default class TranspiledModule {
...
+          ...Array.from(this.transpilationInitiators).map(t =>
+            t.transpile(manager)
+          ),
+          ...Array.from(this.dependencies).map(t => t.transpile(manager)),
+        ])
+      );
 
-    return this;
+      return this;
+    } finally {
```
Comment (CompuIves) [inline packages/app/src/sandbox/eval/transpiled-module.ts]: This is really what I've added, when finished with transpiling we remove it from the transpileJobs.

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3335/commits/18f380b0f9ce47ea146b13902b7b3edbb5c30436 is at https://pr3335.build.csb.dev/s/new.
