### PR TITLE
fix: Use map for transpilers, this resolves an issue with transpilers dissapearing

### LINKED ISSUE #6105: Vue Sandbox suddenly stopped working. Error "Could not find dependency: 'vue-style-loader' relative to '/package.json'"
# 🐛 bug report

## Preflight Checklist
- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Vue Sandbox is suddenly throwing error "Could not find dependency: 'vue-style-loader' relative to '/package.json'". Sandbox hasn't been updated in months so a breaking change in CodeSandbox is suspected.

## How has this issue affected you? What are you trying to accomplish?
This error breaks the sandbox.

### To Reproduce
Visit: https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |a819609e7 |
| Browser          |Edge 93.0.961.38|
| Operating System |Windows 10|

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by DeMoorJasper**
## What kind of change does this PR introduce?

This PR changes the logic of transpilers in a preset to use a (private) map so we ensure full control over when and how transpilers are registered.

The good thing is that this de-duplicates duplicate transpiler registrations so should speedup code execution as well.

For some reason this fixed a case where transpilers dissapear, still not sure how this is even possible?

Fixes #6105

### CODE REVIEW

File: packages/sandpack-core/src/preset/preset.ts [hunk 1]
```diff
@@ -115,10 +115,25 @@ export class Preset {
...
 
     this.postTranspilers.forEach(transpiler => {
-      this.transpilers.add(transpiler.transpiler);
+      this.addTranspiler(transpiler.transpiler);
     });
   }
 
+  private addTranspiler(t: Transpiler) {
+    // TODO: Should this overwrite or skip?
+    if (this._transpilers.has(t.name)) return;
```
Comment (DeMoorJasper) [inline packages/sandpack-core/src/preset/preset.ts:124]: Transpilers should have a unique name so this should be fine?

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/6111/commits/de9f65e04553f4c596ea750616d3635bc22eecbe is at https://pr6111.build.csb.dev/s/new.
