### PR TITLE
fix markdown crash on info

### LINKED ISSUE #4690: Crashing repeatedly while accessing sandbox info
<h1>💥 Crash Report</h1>

  <h2>Crashing sandbox while trying to access sandbox info</h2>

  <h3>Link to sandbox: [Sandbox Link](https://codesandbox.io/s/react-google-maps-demo-nqrkm?file=/src/App.js)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 9fe27eb74          |

  **Route:**
  https://codesandbox.io/s/react-google-maps-demo-nqrkm?file=/src/Map.js

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Failed to construct 'URL': Invalid URL
  TypeError: Failed to construct 'URL': Invalid URL
    at Fi (https://codesandbox.io/static/js/app.4cb763821.js?_sw-precache=7ae713067cc964d2e3bd8d4f09f17aeb:306:935334)
    at ua (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759094)
  
    in Fi
    in p
    in root
    in y
    in div
    in Markdown___StyledElement
    in Vi
    in div
    in styled.div
    in section
    in Styled(styled.div)
    in div
    in styled.div
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in $m
    in div
    in div
    in ProjectInfo___StyledStack
    in project
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by SaraVieira**
closes #4690

An empty link broke the website, wow javascript ah?

### CODE REVIEW

File: packages/app/src/app/components/Markdown/Link.tsx [hunk 1]
```diff
@@ -1,12 +1,22 @@
-import { Button, Link } from '@codesandbox/components';
+import { Button, Link, Text } from '@codesandbox/components';
 import css from '@styled-system/css';
 import { useOvermind } from 'app/overmind';
 import React from 'react';
 
 export const LinkElement = ({ href, children, ...props }) => {
+  let commentId = '';
```
Comment (CompuIves) [inline packages/app/src/app/components/Markdown/Link.tsx:7]: Really small nit: this way `commentId` can be only two things:

1. null
2. a valid comment id

instead of 3 things:

1. null
2. valid comment id
3. empty string

```suggestion
  let commentId = null;
```

**Review by CompuIves — APPROVED** [review]
Looks good! Added a minininini nit, but this is a super nice fix!

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4785/commits/11c2b364e89c811d855bbc4e33fea9e78f884dcd is at https://pr4785.build.csb.dev/s/new.

File: packages/app/src/app/components/Markdown/Link.tsx (hunk 1 above)
Comment (SaraVieira) [reply packages/app/src/app/components/Markdown/Link.tsx:7]: Good catch, changed 👍
