### PR TITLE
Use new preact compat

### LINKED ISSUE #3685: [Template update] Preact template isn't using preact/compat
# 🐛 bug report

## Description of the problem. How has this issue affected you? What are you trying to accomplish?
I tried to use react component like `react-window` in preact sandox which works perfectly fine locally but is not working in codesandbox.

### Root cause
Preact transpiler is currently using `preact-compat` instead of `preact/compat` (Required for Preact 10). I think we just need to fix this file https://github.com/codesandbox/codesandbox-client/blob/a616fcf3fd31eb75ee40451fbf9c2beb936b9559/packages/app/src/sandbox/eval/presets/preact-cli/index.js#L20
I will send PR soon after testing.

### Your Environment
N/A. This issue is related to preact template

### PR DESCRIPTION
**Pull request by SaraVieira**
Closes #3685

Test sandbox
https://pr4914.build.csb.dev/s/preact-template-compat-issue-forked-jd3yo?file=/src/index.js

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4914/commits/23d37b4f5f50abf6dde564bc6327afd0f0924322 is at https://pr4914.build.csb.dev/s/new.

File: packages/app/src/sandbox/eval/presets/preact-cli/preset.js [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+      'create-react-class': 'preact/compat/lib/create-react-class',
+      'react-addons-css-transition-group': 'preact-css-transition-group',
+    }
+  );
+
+  preactPreset.registerTranspiler(module => /\.m?jsx?$/.test(module.path), [
+    {
+      transpiler: babelTranspiler,
+      options: {
+        isV7: false,
```
Comment (CompuIves) [inline packages/app/src/sandbox/eval/presets/preact-cli/preset.js:31]: I believe that the newest `preact-cli` is on version 7 of Babel nowadays, would be good to check their babel config and update this one to the new one.

File: packages/app/src/sandbox/eval/presets/preact-cli/old.js [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+import sassTranspiler from '../../transpilers/sass';
+import rawTranspiler from '../../transpilers/raw';
+import stylusTranspiler from '../../transpilers/stylus';
+import lessTranspiler from '../../transpilers/less';
+
+import asyncTranspiler from './transpilers/async';
+
+import Preset from '..';
+
+export default function PreactPresetOld() {
```
Comment (CompuIves) [inline packages/app/src/sandbox/eval/presets/preact-cli/old.js:13]: We should add a bit more descriptive name, because `old` can mean anything. Maybe something like `preactV9` or something?

**Review by CompuIves — CHANGES_REQUESTED** [review]
This is really great! I like the approach, and it fits well with existing approaches. I left a comment about a name, and the second thing I would do is update the config of the new Preact template. Because I don't think we match it anymore. We can copy it over from here, I can do that: https://github.com/preactjs/preact-cli/blob/master/packages/cli/lib/lib/babel-config.js.

File: packages/app/src/sandbox/eval/presets/preact-cli/preset.js (hunk 1 above)
Comment (SaraVieira) [reply packages/app/src/sandbox/eval/presets/preact-cli/preset.js]: updated but now I get a babel error

File: packages/app/src/sandbox/eval/presets/preact-cli/old.js (hunk 2 above)
Comment (SaraVieira) [reply packages/app/src/sandbox/eval/presets/preact-cli/old.js]: Changed to v8 since there was no version 9

File: packages/app/src/sandbox/eval/presets/preact-cli/preset.js (hunk 1 above)
Comment (SaraVieira) [reply packages/app/src/sandbox/eval/presets/preact-cli/preset.js]: pr4914.build.csb.dev/s/preact-template-compat-issue-forked-jd3yo?file=/src/index.js

File: packages/common/src/templates/configuration/babelrc/index.ts [hunk 3]
```diff
@@ -18,17 +19,46 @@ const config: ConfigurationFile = {
     resolveModule: (path: string) => { code: string } | undefined
   ) => {
     let isV7 = false;
+    let isP10 = false;
```
Comment (CompuIves) [inline packages/common/src/templates/configuration/babelrc/index.ts:22]:
```suggestion
    let isPreact10 = false;
```

File: packages/common/src/templates/configuration/babelrc/index.ts [hunk 4]
```diff
@@ -18,17 +19,46 @@ const config: ConfigurationFile = {
...
 
     try {
       const packageJSON = resolveModule('/package.json');
       const parsed = JSON.parse(packageJSON.code || '');
 
       isV7 = isBabel7(parsed.dependencies, parsed.devDependencies);
+      isP10 = isPreact10(parsed.dependencies, parsed.devDependencies);
```
Comment (CompuIves) [inline packages/common/src/templates/configuration/babelrc/index.ts:29]:
```suggestion
      isPreact10 = isPreact10(parsed.dependencies, parsed.devDependencies);
```

File: packages/common/src/templates/configuration/babelrc/index.ts [hunk 5]
```diff
@@ -18,17 +19,46 @@ const config: ConfigurationFile = {
...
     } catch (e) {
       console.error(e);
     }
 
     if (template === 'preact-cli') {
+      if (isP10) {
```
Comment (CompuIves) [inline packages/common/src/templates/configuration/babelrc/index.ts:35]:
```suggestion
      if (isPreact10) {
```

**Review by CompuIves — APPROVED** [review]
Great!
