### PR TITLE
fix 5282

### LINKED ISSUE #5282: Crashes when Fork-> Rename-> Move
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

[codesandbox-fork-with-move-bug](https://codesandbox.io/s/codesandbox-fork-with-move-bug-cm858)
  <h3>Link to sandbox: </h3>
I have sent a link to the file it crashed with. However, I do not believe it is a file/code specific content issue, as it has happened on different files and content.
  <h3>Crash Details</h3>

I sometimes get a program crash error and I decided to recreate it and send it to you.

This happens when you fork an existing file, rename the file and press enter. If you do not allow the 'rename' function/code to finish executing in the background and then immediately click on 'move folder/item' to move the renamed file to another folder, the program will give you a 'crash error'. (You may also lose the 'file' you renamed).

**Possible Solution:**  Prevent user from applying 'Move item' feature until 'rename' code has finished executing. 
  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 87.0.4280 | Windows 10           | d00f3b4ac          |

  **Route:**
  https://codesandbox.io/s/codesandbox-fork-with-move-bug-rename-9g88x

  **Error Code:**
c5148dd38ca944e1a4aa4986b4e39306

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of null
  TypeError: Cannot read property 'id' of null
    at We (https://codesandbox.io/static/js/move-sandbox-modal.dbc9cf8ac.chunk.js?_sw-precache=dc9708efc97efec67dde7d93654414a6:22:27152)
    at ua (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1780850)
    at xs (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1826113)
    at ml (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1811689)
    at hl (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1811614)
    at il (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1808942)
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1767125
    at https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1842461
    at qo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1767005)
    at el (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1805728)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:1771829)
    at r.setState (https://codesandbox.io/static/js/common.6505fbdb5.chunk.js?_sw-precache=b712b3271fca4c1e2579663dbbc347aa:1:2025481)
    at https://codesandbox.io/static/js/default~app~embed.650f925fe.chunk.js?_sw-precache=ec2f1e09ce019c5d3e6edec4da4c661e:499:142156
  
    in We
    in r
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by SaraVieira**
Adds a check for activeTeam before opening the modal

closes #5282

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5289/commits/0e3d7744bf5ebabab3415053918611f31e094214 is at https://pr5289.build.csb.dev/s/new.

File: packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx [hunk 1]
```diff
@@ -19,20 +19,23 @@ import { DirectoryPicker } from './DirectoryPicker';
...
     modals.moveSandboxModal.defaultOpenedPath
   );
   const [teamId, setTeamId] = useState(activeTeam);
-
-  const [selectedTeam, setSelectedTeam] = useState({
-    id: activeTeamInfo.id,
-    name: activeTeamInfo.name,
-    avatarUrl: activeTeamInfo.avatarUrl,
-  });
+  const [selectedTeam, setSelectedTeam] = useState(
```
Comment (CompuIves) [inline packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx:30]: This could break the modal I think. If this happens

1. Modal renders without `activeTeamInfo`
2. `activeTeamInfo` becomes available
3. Now it's not in the modal

Is that a flow that would break?

**Review by CompuIves — COMMENTED** [review]
I saw one bug with the approach, but maybe it doesn't break anything?

File: packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx (hunk 1 above)
Comment (CompuIves) [reply packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx:30]: Yeah I think then the modal will never render if team is not available.

Comment (CompuIves) [reply packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx:30]: Probably the check needs to be one leve higher

```
{activeTeamInfo && <MoveSandboxModal />}
```

Comment (SaraVieira) [reply packages/app/src/app/pages/common/Modals/MoveSandboxFolderModal/index.tsx:30]: https://github.com/codesandbox/codesandbox-client/pull/5292
