### PR TITLE
fix crash

### LINKED ISSUE #4813: It crashed when I entered the 6 digit code
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 81.0.0 | OS X 10.15           | 52a7192ff          |

  **Route:**
  https://codesandbox.io/s/competent-black-8rlhb

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: can't access property "id", e is undefined
  Wn/r<@https://codesandbox.io/static/js/app.b6049c787.js:306:869354
Wn@https://codesandbox.io/static/js/app.b6049c787.js:306:869330
ua@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874
Es@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137
ml@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803715
hl@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638
il@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966
$o/<@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485
qo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858
$o@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759096
Yo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759029
el@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797752
Sa@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1776549
.forceRerender<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1050314
d/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1050996
track/this.callback@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1172448
flush@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1175278
flush@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1171502
g/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1060110
../../node_modules/overmind/es/index.js/o</e.prototype.emit@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1053753
createAction/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1062743
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1061786
e/<@https://codesandbox.io/static/js/app.b6049c787.js:306:445421
l@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255487
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090
t@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2617
../../node_modules/@babel/runtime/helpers/asyncToGenerator.js/e.exports/</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2676
../../node_modules/@babel/runtime/helpers/asyncToGenerator.js/e.exports/<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
./src/app/overmind/index.ts/Oe</<@https://codesandbox.io/static/js/app.b6049c787.js:306:445915
createAction/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1062676
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1061786
e/<@https://codesandbox.io/static/js/app.b6049c787.js:306:446344
l@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255487
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090
t@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2617

  
    in Wn
    in div
    in Actions___StyledStack
    in xr
    in header
    in Header___StyledStack
    in Oa
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4814: crash when logging in with an active sandbox
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>
log in

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 80.0.0 | Ubuntu           | 926e6e0d2          |

  **Route:**
  https://codesandbox.io/s/affectionate-yalow-sujx3?file=/index.html

  **Error Code:**
6945f34f57794f80b2f4b11ee68162a8

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: e is undefined
  Wn/r<@https://codesandbox.io/static/js/app.22c21a658.js:306:870044
Wn@https://codesandbox.io/static/js/app.22c21a658.js:306:870020
ua@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874
Es@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137
ml@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803715
hl@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638
il@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966
$o/<@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485
qo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858
$o@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759096
Yo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759029
el@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797752
Sa@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1776549
.forceRerender<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1050314
d/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1050996
track/this.callback@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1172448
flush@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1175278
flush@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1171502
g/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1060110
../../node_modules/overmind/es/index.js/o</e.prototype.emit@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1053753
createAction/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1062743
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1061786
e/<@https://codesandbox.io/static/js/app.22c21a658.js:306:445978
l@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255487
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090
t@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2617
../../node_modules/@babel/runtime/helpers/asyncToGenerator.js/e.exports/</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2676
../../node_modules/@babel/runtime/helpers/asyncToGenerator.js/e.exports/<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
./src/app/overmind/index.ts/Ie</<@https://codesandbox.io/static/js/app.22c21a658.js:306:446472
createAction/<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1062676
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js:1:1061786
e/<@https://codesandbox.io/static/js/app.22c21a658.js:306:446901
l@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255487
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090
t@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2617

  
    in Wn
    in div
    in Actions___StyledStack
    in xr
    in header
    in Header___StyledStack
    in Oa
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4815: crash report codesandbox react
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 926e6e0d2          |

  **Route:**
  https://codesandbox.io/s/new

  **Error Code:**
f606bceb10b6401f9285425398a8d8d1

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'id' of undefined
  TypeError: Cannot read property 'id' of undefined
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:870053
    at Array.map (<anonymous>)
    at Wn (https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:870020)
    at ua (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874)
    at Es (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1818137)
    at ml (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803713)
    at hl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858)
    at $o (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759029)
    at el (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797752)
    at Sa (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1776547)
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050313
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1050996
    at https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1172448
    at m.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1175277)
    at p.flush (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1171502)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1060110)
    at e.emit (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1053753)
    at dashboard.getTeams (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062743)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:445978
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2675
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2556
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:446472
    at internal.initializeNewUser (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1062675)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.8a619e6d0.chunk.js?_sw-precache=2213ea3572f634ccadff0a58c3ac202e:1:1061785)
    at https://codesandbox.io/static/js/app.22c21a658.js?_sw-precache=15dda38ef6014080001dd838cd7fd39c:306:446901
    at l (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255486)
    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090)
    at t (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405)
    at i (https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2616)
  
    in Wn
    in div
    in Actions___StyledStack
    in xr
    in header
    in Header___StyledStack
    in Oa
    in je
    in Unknown
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by SaraVieira**
closes #4814 
closes #4813
closes #4815

https://sentry.io/organizations/codesandbox/issues/1875124926/events/6945f34f57794f80b2f4b11ee68162a8/?project=2071895&statsPeriod=14d

### CODE REVIEW

File: packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx [hunk 1]
```diff
@@ -106,98 +106,116 @@ interface ForkButtonProps {
 export const ForkButton: React.FC<ForkButtonProps> = props => {
   const { state } = useOvermind();
   const { user } = props;
+  let teams: TeamItem[] = [];
+  let currentSpace: TeamItem = null;
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx:110]:
```suggestion
  let currentSpace: TeamItem | null = null;
```

File: packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx [hunk 2]
```diff
@@ -106,98 +106,116 @@ interface ForkButtonProps {
...
+  }[] = [
     userSpace,
     ...state.dashboard.teams.filter(t => t.id !== state.personalWorkspaceId),
-  ].map(team => ({
-    teamId: team.id,
-    teamName: team.name,
-    teamAvatar: team.avatarUrl,
-    userAuthorizations: team.userAuthorizations,
-  }));
+  ];
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Header/ForkButton/ForkButton.tsx:125]: Since `userSpace` can be null (I think?)

```suggestion
  ].filter(Boolean);
```

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4816/commits/cf8dc06a7e09f47b8276d849141417d6d6468b30 is at https://pr4816.build.csb.dev/s/new.

**Review by CompuIves — COMMENTED** [review]
Nice!! Two small things

**Comment by SaraVieira** [comment]
Both added
