### PR TITLE
Use app logic for loading default file in embed

### LINKED ISSUE #2091: README.md does not display in embed when selected as "default module to show".
# 🐛 bug report

## Description of the problem

When sharing a CodeSandbox, I clicked `README.md` to display as the default module users see when the embed opens. However, a random file is displayed instead of the `README.md`.

### Steps to reproduce
- Open [CodeSandbox](https://codesandbox.io/embed/code-challenge-uhz9n)
- Click _Share_
- In the _Configure_ section of the modal, click on _Sandbox options_
- In the _Default module to show_ section, click on `README.md`

In my case, `tests/state/reducers/gameReducer.js` shows, not `README.md` from the root directory.

## How has this issue affected you? What are you trying to accomplish?

This CodeSandbox is a solution to an interview problem. When the reviewing developer opens my solution, I'd like them to show them the `README.md`. The `README.md` shows my ability to write documentation and includes notes about my implementation.

Outside of the reviewing developer, visitors to the embed may be unfamiliar with [Conway's Game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life). The `README.md` includes information about the purpose, rules, and gameplay.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1561388488-a3b21c078|
| Browser          | Chrome Version 75.0.3770.100 (Official Build) (64-bit)
| Operating System |macOS Mojave 10.14.4

### PR DESCRIPTION
**Pull request by siddharthkp**
## What kind of change does this PR introduce?

Bugfix, Fixes #2091

## What is the current behavior?

There is a concept of "mainModule" when sharing a sandbox. For node project without a clear `index.js` file, this will default to `README.md`. Example: [/s/code-challenge-uhz9n](https://codesandbox.io/s/code-challenge-uhz9n)

This is the file that the editor in sandbox will open by default.

However, in the case of embed, if the entry file doesn't exist, it falls back to the first available file (`modules[0]`). This often opens an unexpected (sometimes deeply nested) file. Example: [/embed/code-challenge-uhz9n](https://codesandbox.io/embed/code-challenge-uhz9n)

## What is the new behavior?

We do have the concept of the concept of [defaultOpenedFiles](https://github.com/codesandbox/codesandbox-client/blob/master/packages/common/src/templates/template.ts#L191-L195) which is a list of potential default options (including README)

Using that as a fallback before `modules[0]` is a better result. Demo: [/staging/embed/code-challenge-uhz9n](https://pr2382.build.csb.dev/embed/code-challenge-uhz9n)

**Doubt**: is it weird that `sandbox.entry` is set to a file that doesn't exist? Does this come from the files in the sandbox or template configuration? 🤔 

## What steps did you take to test this?

- [x] Tested embed without module in URL
- [x] Tested embed with module in URL
- [x] Testing embed with node sandbox
- [x] Testing embed with react sandbox
- [x] Checked if this affects `/s`, seems to be fine 

## Checklist

- NA Documentation
- [x] Testing 
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

File: packages/app/src/embed/components/App/index.js [hunk 1]
```diff
@@ -225,13 +225,16 @@ export default class App extends React.PureComponent<
...
+      sandbox.directories,
+      currentModulePath,
+      findMainModule(
         sandbox.modules,
         sandbox.directories,
-        currentModulePath,
-        findMainModule(sandbox.modules, sandbox.directories, sandbox.entry)
-      ) || sandbox.modules[0]
+        sandbox.entry,
+        sandbox.template
```
Comment (siddharthkp) [inline packages/app/src/embed/components/App/index.js]: `Notes for reviewer`: Pass `sandbox.template` to use in attempt to find `mainModule`

File: packages/app/src/embed/components/Content/index.tsx [hunk 2]
```diff
@@ -387,7 +387,12 @@ export default class Content extends React.PureComponent<Props, State> {
     } = this.props;
 
     const mainModule = isInProjectView
-      ? findMainModule(sandbox.modules, sandbox.directories, sandbox.entry)
+      ? findMainModule(
+          sandbox.modules,
+          sandbox.directories,
+          sandbox.entry,
+          sandbox.template
```
Comment (siddharthkp) [inline packages/app/src/embed/components/Content/index.tsx]: `Notes for reviewer`: Not sure what Content does with this information, but keeping it consistent with App

File: packages/common/src/sandbox/modules.ts [hunk 3]
```diff
@@ -251,14 +252,30 @@ export const isMainModule = (
...
-  entry: string = 'index.js'
+  entry: string = 'index.js',
+  template?: TemplateType
 ) => {
   try {
+    // first attempt: try loading the entry file if it exists
     const module = resolveModule(entry, modules, directories);
-
     return module;
   } catch (e) {
```
Comment (siddharthkp) [inline packages/common/src/sandbox/modules.ts]: ugh nested try catch. Is there a better way to handle this? This looks ugly.

File: packages/common/src/sandbox/modules.ts [hunk 4]
```diff
@@ -284,3 +301,19 @@ export const findCurrentModule = (
     mainModule
   );
 };
+
+export const resolveModuleWrapped = sandbox => (path: string) => {
```
Comment (siddharthkp) [inline packages/common/src/sandbox/modules.ts]: Moved these 2 utils from `templates/configuration/resolve-module-wrapped.ts`, needed to use one of them. This feels like a nicer home for them.

File: packages/common/src/sandbox/modules.ts [hunk 5]
```diff
@@ -251,14 +252,30 @@ export const isMainModule = (
 export const findMainModule = (
   modules: Module[],
   directories: Directory[],
-  entry: string = 'index.js'
+  entry: string = 'index.js',
+  template?: TemplateType
 ) => {
   try {
+    // first attempt: try loading the entry file if it exists
     const module = resolveModule(entry, modules, directories);
```
Comment (MichaelDeBoey) [inline packages/common/src/sandbox/modules.ts]: You can just directly return this, no? 🤔

File: packages/common/src/sandbox/modules.ts [hunk 6]
```diff
@@ -251,14 +252,30 @@ export const isMainModule = (
...
   } catch (e) {
-    return modules[0];
+    try {
+      // second attempt: try loading the first file that exists from
+      // the list of possible defaults in the template defination
+      const templateDefinition = getTemplateDefinition(template);
+
+      const defaultOpenedFiles = templateDefinition.getDefaultOpenedFiles({});
+
+      const defaultOpenModule = defaultOpenedFiles
```
Comment (MichaelDeBoey) [inline packages/common/src/sandbox/modules.ts]: Same

File: packages/common/src/sandbox/modules.ts (hunk 5 above)
Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Can do

File: packages/common/src/sandbox/modules.ts (hunk 6 above)
Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Can, but wanted to use the variable name as an excuse to label the value

**Comment by siddharthkp** [comment]
@MichaelDeBoey @CompuIves @Saeris Is the right direction to go into? Running on a hunch here.

File: packages/common/src/sandbox/modules.ts (hunk 6 above)
Comment (MichaelDeBoey) [reply packages/common/src/sandbox/modules.ts]: I think ESLint will complain too if I'm not mistaken

Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Doesn't look like it 😇

Comment (CompuIves) [reply packages/common/src/sandbox/modules.ts]: Hmm yes I like this clear variable name, good documentation.

File: packages/common/src/sandbox/modules.ts [hunk 7]
```diff
@@ -251,14 +252,30 @@ export const isMainModule = (
...
-
     return module;
   } catch (e) {
-    return modules[0];
+    try {
+      // second attempt: try loading the first file that exists from
+      // the list of possible defaults in the template defination
+      const templateDefinition = getTemplateDefinition(template);
+
+      const defaultOpenedFiles = templateDefinition.getDefaultOpenedFiles({});
```
Comment (CompuIves) [inline packages/common/src/sandbox/modules.ts]: Ah, normally we pass in the parsed configurations (like `package.json`) here, in case it's needed to determine the main file. We use the function `parseSandboxConfigurations` (https://github.com/CompuIves/codesandbox-client/blob/b228282987eb687bf4251c1fb564ec6467e32d6c/packages/app/src/app/store/actions.js#L173) to get these configurations, but that function needs `sandbox`, which is not available here.

It would be good to use the parsed configurations as well, to keep consistency with the editor, but we'd probably need to get another argument here with parsed configurations...

File: packages/common/src/sandbox/modules.ts (hunk 3 above)
Comment (CompuIves) [reply packages/common/src/sandbox/modules.ts]: Hmm, if we use `resolveModuleWrapped` here we can do a nullcheck on the result, move on to the next flow if needed.

File: packages/common/src/templates/configuration/resolve-module-wrapped.ts [hunk 8]
```diff
@@ -1,17 +1,10 @@
...
+} from '../../sandbox/modules';
 
-export const resolveModuleWrapped = sandbox => (path: string) => {
-  try {
-    return resolveModule(path, sandbox.modules, sandbox.directories);
-  } catch (e) {
-    return undefined;
-  }
-};
+// keeping this file around to reduce merge conflicts
```
Comment (CompuIves) [inline packages/common/src/templates/configuration/resolve-module-wrapped.ts]: Smart!

**Comment by lbogdan** [comment]
Should we maybe address #2249 (and the referenced related ones in that issue's description) with this, too?

**Comment by siddharthkp** [comment]
> Should we maybe address #2249 (and the referenced related ones in that issue's description) with this, too?

Yep, seems related. But the change would probably be in templates, not embed. Will attempt this in a different pull request

File: packages/common/src/sandbox/modules.ts (hunk 3 above)
Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Nice, I really like that

File: packages/common/src/sandbox/modules.ts (hunk 7 above)
Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: I couldn't import that exact file because of a cyclic dependency. But was able to repurpose it's implementation.

File: packages/common/src/sandbox/modules.ts [hunk 9]
```diff
@@ -249,34 +250,36 @@ export const isMainModule = (
...
-      // second attempt: try loading the first file that exists from
-      // the list of possible defaults in the template defination
-      const templateDefinition = getTemplateDefinition(template);
+export const findMainModule = (sandbox?: Sandbox) => {
+  const resolve = resolveModuleWrapped(sandbox);
 
-      const defaultOpenedFiles = templateDefinition.getDefaultOpenedFiles({});
+  // first attempt: try loading the entry file if it exists
+  const entryModule = resolve(sandbox.entry);
+  if (entryModule) return entryModule;
```
Comment (MichaelDeBoey) [inline packages/common/src/sandbox/modules.ts]: Put curly braces around body to make this less error-prone.

File: packages/common/src/sandbox/modules.ts [hunk 10]
```diff
@@ -249,34 +250,36 @@ export const isMainModule = (
...
+
+  const defaultOpenedFiles = templateDefinition.getDefaultOpenedFiles(
+    parsedConfigs
+  );
+
+  const defaultOpenModule = defaultOpenedFiles
+    .map(path => resolve(path))
+    .find(module => module);
+
+  if (defaultOpenModule) return defaultOpenModule;
```
Comment (MichaelDeBoey) [inline packages/common/src/sandbox/modules.ts]: Same

File: packages/common/src/sandbox/modules.ts (hunk 9 above)
Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Like this:?

```js
if (entryModule) {
  return entryModule;
}
```

Comment (MichaelDeBoey) [reply packages/common/src/sandbox/modules.ts]: Yes that's what I ment indeed 🙂

Comment (siddharthkp) [reply packages/common/src/sandbox/modules.ts]: Done

**Comment by siddharthkp** [comment]
Merged master (https://github.com/codesandbox/codesandbox-client/pull/2392) in, this should make the build work now.
