### PR TITLE
fix(storage-management): fix behavior outside of a sandbox context

### LINKED ISSUE #3077: Can't delete files in storage management
# 🐛 bug report

Hi, I'm new to this. I wanted to upload to big of a project into sandbox and it exceeded storage space, when I go to storage management to delete files, check them and click the delete selected button, nothing happens.

I tried different browsers. 

| Operating System | MacOs

### PR DESCRIPTION
**Pull request by arthurdenner**
## What kind of change does this PR introduce?
Bug fix. Closes #3077.

## What is the current behavior?
I noticed a few issues on the Storage Management modal:

1. If you select two files, unselect one of them and press to delete, we send the id for both files because we are not filtering which files have `{ [id]: true }`;
2. If you try to delete a file outside the editor, it fails because we try to access `state.editor.currentSandbox.owned` without checking for `currentSandbox` first;
3. If you open the modal outside the editor, the buttons to add files to the project are enabled.

## What is the new behavior?
1. We are only sending the current selected files;
2. We are checking for `currentSandbox` before trying to read `currentSandbox.owned`;
3. We are disabling the button and tooltips for adding files to the project when the modal is opened outside the editor.

### Delete files flow

1. Open the modal outside the editor
2. Select files and press to delete them
3. Verify that the files are deleted.

### Add files flow

1. Open the modal outside the editor
2. Verify that the buttons for adding files are disabled.

## Checklist

- [ ] Documentation
- [ ] Testing 
- [ ] Ready to be merged
      
- [ ] Added myself to contributors table
      

## Notes

I'd rather remove the buttons for adding files when the modal is opened outside the editor, but didn't took this route because it would required more changes and I'd like to get your feedback.

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3081/commits/79259dc8ca85850d70e1fe5a46319f20e6d96aba is at https://pr3081.build.csb.dev/s/new.

File: packages/app/src/app/overmind/factories.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export const withOwnedSandbox = <T>(
 ): AsyncAction<T> => async (context, payload) => {
   const { state, actions } = context;
 
-  if (!state.editor.currentSandbox.owned) {
```
Comment (CompuIves) [inline packages/app/src/app/overmind/factories.ts]: Makes sense! Could you wrap this in a single `if` statement? `if (state.editor.currentSandbox` and then the other if statements. I think that's a bit cleaner and less duplication.
