### PR TITLE
Fix " Failed to execute 'removeChild' on 'Node'" errors

### LINKED ISSUE #4643: crash
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 850d9b1b5          |

  **Route:**
  https://codesandbox.io/s/html-code-editor-b3sgf?file=/index.html

  **Error Code:**
f3368a0df10c4e9c99fe26a4c8df03ad

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1752881)
    at ms (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1750882)
    at ys (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1752618)
    at yl (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1771883)
    at https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1793415
    at qo (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1717788)
    at bl (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1769768)
    at il (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1760095)
    at https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1718079
    at https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1793415
    at qo (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1717788)
    at Yo (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1718024)
    at $o (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1717959)
    at ce (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1787370)
    at On (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1701917)
    at Mn (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1702874)
    at Tn (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1702162)
    at https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1793415
    at jn (https://codesandbox.io/static/js/common.d7bb3d59f.chunk.js?_sw-precache=be1686a7519f9a709d61b74817801e6b:1:1701638)
  
    in Styled(Component)
    in div
    in Xl
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in Unknown
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in ru
    in au
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4663: crash
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | caab652ef          |

  **Route:**
  https://codesandbox.io/s/romantic-darkness-bev07

  **Error Code:**
5cb81e9b56e141539934109d0710e5a9

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1793951)
    at ms (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1791952)
    at ys (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1793688)
    at yl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1812953)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1834485
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1758858)
    at bl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1810838)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1801165)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1759149
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1834485
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1758858)
    at $o (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1759094)
    at Yo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1759029)
    at ce (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1828440)
    at On (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1742987)
    at Mn (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1743944)
    at Tn (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1743232)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1834485
    at jn (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js?_sw-precache=9db6b139f347684d322a253d829c3091:1:1742708)
  
    in Styled(Component)
    in div
    in Xl
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in div
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in ru
    in au
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4692: Big crash codesandbox impossible to work on, erase the job without doing any manipulation and impossible to save before
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | b3f4f6556          |

  **Route:**
  https://codesandbox.io/s/techchallenge-web-dev-starter-forked-nkitk

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1793951)
    at ms (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1791952)
    at ys (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1793688)
    at yl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1812953)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
    at qo (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1758858)
    at bl (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1810838)
    at il (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1801165)
    at https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1759149
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.1a4d639f7.chunk.js:1:1834485)
  
    in Styled(Component)
    in div
    in Xl
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in div
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in ru
    in au
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4735: sandbox not working
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 17ade25cd          |

  **Route:**
  https://codesandbox.io/u/fourneau/sandboxes

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1793951)
    at ms (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1791952)
    at ys (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1793688)
    at yl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1812953)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
    at qo (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1758858)
    at bl (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1810838)
    at il (https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1801165)
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1759149
    at https://codesandbox.io/static/js/common.2ec6ed680.chunk.js?_sw-precache=59f41a455ec099cde5056c6e8bec7a07:1:1834485
  
    in div
    in Kn
    in t
    in t
    in div
    in elements__Margin
    in div
    in styled.div
    in div
    in styled.div
    in Unknown
    in div
    in elements__Container
    in Ht
    in r
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4909: error de choque
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 75ad6385c          |

  **Route:**
  https://codesandbox.io/s/frosty-architecture-zsylv?file=/src/components/perfil.vue

  **Error Code:**
4d8cb88b6c8e498c81498116bbf03cc1

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1790178)
    at ms (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1788179)
    at ys (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1789915)
    at yl (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1809180)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at qo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755085)
    at bl (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1807065)
    at il (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1797392)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755376
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at qo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755085)
    at Xo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755321)
    at Yo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755256)
    at ce (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1824667)
    at On (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1739214)
    at Mn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1740171)
    at Tn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1739459)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at jn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1738935)
  
    in Styled(Component)
    in div
    in es
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in div
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in zs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in zs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in iu
    in cu
    in div
    in Be
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in Be
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Be
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4932: Error
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 006adee03          |

  **Route:**
  https://codesandbox.io/s/new-sun-syoht

  **Error Code:**
623cee9f05c341eaac7b2fe7cb30a679

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1790178)
    at ms (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1788179)
    at ys (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1789915)
    at yl (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1809180)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at qo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755085)
    at bl (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1807065)
    at il (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1797392)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755376
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at qo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755085)
    at Xo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755321)
    at Yo (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1755256)
    at ce (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1824667)
    at On (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1739214)
    at Mn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1740171)
    at Tn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1739459)
    at https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1830712
    at jn (https://codesandbox.io/static/js/common.5b5b604ac.chunk.js?_sw-precache=5d0eeb242fe46087b2105694f97d4dde:1:1738935)
  
    in Styled(Component)
    in div
    in Ps
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in div
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in yu
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in yu
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in zu
    in Vu
    in div
    in Be
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in Be
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in Be
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4934: crash
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 80cecb15a          |

  **Route:**
  https://codesandbox.io/s/html-code-editor-forked-27qbe?file=/index.html

  **Error Code:**
c62e04e781b948a797d5caf18334209c

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1791020)
    at ms (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1789021)
    at ys (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1790757)
    at yl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1810022)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1831554)
    at qo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1755927)
    at bl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1807907)
    at il (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1798234)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1756218
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js:1:1831554)
  
    in Styled(Component)
    in div
    in Ps
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in div
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in yu
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in zu
    in Vu
    in div
    in De
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

### LINKED ISSUE #4947: eitaaa
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 85.0.4183 | Windows 10           | 36769386e          |

  **Route:**
  https://codesandbox.io/s/objective-keldysh-fslfg

  **Error Code:**
bf869df26051446695af0fa5784bc8f1

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1791020)
    at yl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1810022)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1831554
    at qo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1755927)
    at bl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1807907)
    at il (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1798234)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1756218
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1831554
    at qo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1755927)
    at Xo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1756163)
  
    in Unknown
    in div
    in Styled(styled.div)
    in div
    in elements__Main
    in ba
    in header
    in Header___StyledStack
    in Oa
    in De
    in Unknown
    in div
    in elements__Container
    in De
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

### PR DESCRIPTION
**Pull request by SaraVieira**
So this error happens when fragments render with no children and react doesn't like that.

I went through all the Fragments we have and fix all the ones that can possibly render null

This will close all those issues

closes #4643
closes #4735
closes #4692
closes #4663
closes #4934
closes #4909
closes #4932
closes #4947

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/4950/commits/8eaf36c85b614ff1e4f4d64212520da743fa917d is at https://pr4950.build.csb.dev/s/new.

File: packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ThankYou/index.tsx [hunk 1]
```diff
@@ -18,13 +18,9 @@ export const ThankYou: React.FC<ThankYouProps> = ({
...
-      {markedAsCancelled ? (
-        'Your subscription will be automatically cancelled before your next billing date.'
-      ) : (
-        <>
-          Thank you <strong>so</strong> much for your support of ${price}!
-        </>
-      )}
+      {markedAsCancelled
+        ? 'Your subscription will be automatically cancelled before your next billing date.'
+        : `Thank you <strong>so</strong> much for your support of ${price}!`}
```
Comment (CompuIves) [inline packages/app/src/app/pages/Patron/PricingModal/PricingChoice/ThankYou/index.tsx:23]: This will render `strong` has well. maybe something like this?

```suggestion
        : <span>Thank you <strong>so</strong> much for your support of {price}!</span>}
```

File: packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx [hunk 2]
```diff
@@ -71,7 +71,7 @@ export const User: FunctionComponent<Props> = ({ liveRole, user }) => {
 
       <Stack align="center" className="live-actions" gap={2}>
         {canChangeEditors ? (
-          <>
+          <div>
```
Comment (christianalfoni) [inline packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx:74]: Not sure if this change is better? Now we are adding a wrapping `div`, but previously it only renders exactly what it needs? Could also change it to: `{canChangeEditors && liveRole === 'spectator' ? ...}` and then next line: `{canChangeEditors && liveRole === 'editor' ? ...}`, makes it even more explicit I think.

**Review by christianalfoni — COMMENTED** [review]
This generally looks good, just one comment 😄

File: packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx (hunk 2 above)
Comment (SaraVieira) [reply packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx]: Moved to a new small component at the top :)

Comment (christianalfoni) [reply packages/app/src/app/pages/Sandbox/Editor/Workspace/screens/Live/LiveNow/User.tsx]: Looks great! 👍  All good from me!

File: packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx [hunk 3]
```diff
@@ -139,7 +139,7 @@ export const Navigation: FunctionComponent<Props> = ({
     >
       <SingletonTooltip placement="right">
         {singleton => (
-          <>
```
Comment (CompuIves) [inline packages/app/src/app/pages/Sandbox/Editor/Navigation/Navigation.tsx:142]: I think we can't change this one, as the Container is a flexbox. But it shouldn't be a problem to make this `<></>` as `WorkspaceItems` will always be filled.

**Review by CompuIves — CHANGES_REQUESTED** [review]
One change, then it's a 👍 !

File: packages/app/src/app/pages/common/LikeHeart/MaybeTooltip.tsx [hunk 4]
```diff
@@ -17,5 +17,5 @@ export const MaybeTooltip: FunctionComponent<Props> = ({
       {children}
     </Tooltip>
   ) : (
-    <>{children}</>
+    <span>{children}</span>
```
Comment (MichaelDeBoey) [inline packages/app/src/app/pages/common/LikeHeart/MaybeTooltip.tsx:20]:
```suggestion
    children
```

**Review by MichaelDeBoey — APPROVED** [review]
