### PR TITLE
Fix vue re-exports

### LINKED ISSUE #5632: Importing a named export returns undefined when there's default and named exports
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
(At least starting with a Vue template) If you try to import a named export from a component (where there's also the default export of the component per se), you always end up with `undefined`

## How has this issue affected you? What are you trying to accomplish?
Cannot declare shared variables between components.

### To Reproduce
In the provided sandbox, look at the console output. The variable "testExport" is imported in `App.vue` from `components/HelloWorld.vue`.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Firefox 87.0
| Operating System | Windows 10

### PR DESCRIPTION
**Pull request by DeMoorJasper**
## What kind of change does this PR introduce?

This PR resolves the issue described here: #5632

It also cleans up the vue transpiler a bit as we don't need any of the esModule logic as we don't support esModule and probably never will for sandpack

Fixes #5632

## Checklist

- [x] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

File: packages/app/src/sandbox/eval/transpilers/vue/v2/component-normalizer.js [hunk 1]
```diff
@@ -13,19 +13,22 @@ module.exports = function normalizeComponent(
...
-  var scriptExports = (rawScriptExports = rawScriptExports || {});
+  let scriptExports = (rawScriptExports = rawScriptExports || {});
 
   // ES6 modules interop
-  var type = typeof rawScriptExports.default;
-  if (type === 'object' || type === 'function') {
-    esModule = rawScriptExports;
-    scriptExports = rawScriptExports.default;
-  }
+  //   let type = typeof rawScriptExports.default;
```
Comment (DeMoorJasper) [inline packages/app/src/sandbox/eval/transpilers/vue/v2/component-normalizer.js:19]: Is this even necessary? Doesn't babel handle this for imports anyway?

Comment (DeMoorJasper) [reply packages/app/src/sandbox/eval/transpilers/vue/v2/component-normalizer.js:19]: In case it is, I changed the logic in the comment to reassign other exports to the object or function it returns but it's not super reliable

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/5798/commits/18e3f9b6ff9782f4dac36f2a4066f2ffd8942883 is at https://pr5798.build.csb.dev/s/new.

File: packages/app/src/sandbox/eval/transpilers/vue/v2/component-normalizer.js [hunk 2]
```diff
@@ -13,19 +13,12 @@ module.exports = function normalizeComponent(
   scopeId,
   moduleIdentifier /* server only */
 ) {
-  var esModule;
-  var scriptExports = (rawScriptExports = rawScriptExports || {});
-
-  // ES6 modules interop
```
Comment (DeMoorJasper) [inline packages/app/src/sandbox/eval/transpilers/vue/v2/component-normalizer.js:19]: Removed this as Babel already handles this on import using `_interopRequireDefault`, if I'm missing something I can revert this change and assign additional exports to the default export

**Review by CompuIves — APPROVED** [review]
Great!! Looks good! :shipit:
