### PR TITLE
fix(tests): apply correct opacity to sync icon when watching tests

### LINKED ISSUE #3002: State of button to "Toggle File Watching" for tests is not visible
# 🐛 bug report

## Description of the problem

In Tests Panel, the state of the "Toggle File Watching" for tests is not clear. It is supposed to have a different opacity whether the option is active or not, but the opacity is left unchanged in any case.

image

The related source code is here: https://github.com/codesandbox/codesandbox-client/blob/3bb3cf34b2ea7f88bab070cd68987005f12b6c1b/packages/app/src/app/components/Preview/DevTools/Tests/TestSummary/elements.ts#L52

Unfortunately I don't know how styled components work so I cannot fix and PR myself.

## How has this issue affected you? What are you trying to accomplish?

Not knowing if the button is active or not is frustrating, especially on projects with hundreds of tests.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | don't know how to find it
| Browser          | latest Chrome
| Operating System | Windows 7

### PR DESCRIPTION
**Pull request by arthurdenner**
## What kind of change does this PR introduce?
Bug fix. Closes #3002.

## What is the current behavior?
The sync's icon opacity doesn't change regardless of the `watching` state.

## What is the new behavior?
It changes as expected. I used the [documented styled-components hack to override higher specificity](https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) applied by the `Actions` component targeting `svg` tags.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

1. Visit [this sandbox](https://codesandbox.io/s/formation-javascript-avance-vnsp4);
2. Toggle file watching for tests;
3. Verify that the opacity changes as expected.

## Checklist

- [ ] Documentation
- [x] Testing 
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by lbogdan** [comment]
Build for latest commit https://github.com/codesandbox/codesandbox-client/pull/3033/commits/554cbf0074e687f54221ff9c3e6eeea98de2c7a2 is at https://pr3033.build.csb.dev/s/new.

File: packages/app/src/app/components/Preview/DevTools/Tests/TestSummary/elements.ts [hunk 1]
```diff
@@ -49,13 +49,9 @@ export const TestData = styled.div`
...
 
 export const SyncIconStyled = styled(SyncIcon)<{ watching: boolean }>`
-  opacity: 0.7;
-  color: ${props => props.theme['button.hoverBackground']};
-  ${props =>
-    props.watching &&
-    css`
-      opacity: 1;
-    `}
+  && {
```
Comment (CompuIves) [inline packages/app/src/app/components/Preview/DevTools/Tests/TestSummary/elements.ts]: Whoah I haven't seen this before, what does `&&` do?

Comment (arthurdenner) [reply packages/app/src/app/components/Preview/DevTools/Tests/TestSummary/elements.ts]: This is new for me too. It's a hacky way to override higher specificity. See [the docs](https://www.styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity) and [this issue](https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693). You can use how many `&` you want. 🤣
